mpi:
  - nompi
  - impi  # [win]
  - mpich  # [unix]
  - openmpi  # [unix]
# https://github.com/conda-forge/opencv-feedstock/issues/493
MACOSX_SDK_VERSION:  # [osx]
  - 15.5             # [osx]

fortran_compiler:   # [win]
    - ifx           # [win]

fortran_compiler_version:  # [win]
    - '2025.*'           # [win]