# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_fortran_compiler_version7mpimpich:
        CONFIG: osx_64_fortran_compiler_version7mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_fortran_compiler_version7mpinompi:
        CONFIG: osx_64_fortran_compiler_version7mpinompi
        UPLOAD_PACKAGES: 'True'
      osx_64_fortran_compiler_version7mpiopenmpi:
        CONFIG: osx_64_fortran_compiler_version7mpiopenmpi
        UPLOAD_PACKAGES: 'True'
      osx_64_fortran_compiler_version9mpimpich:
        CONFIG: osx_64_fortran_compiler_version9mpimpich
        UPLOAD_PACKAGES: 'True'
      osx_64_fortran_compiler_version9mpinompi:
        CONFIG: osx_64_fortran_compiler_version9mpinompi
        UPLOAD_PACKAGES: 'True'
      osx_64_fortran_compiler_version9mpiopenmpi:
        CONFIG: osx_64_fortran_compiler_version9mpiopenmpi
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 600

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)